### PR TITLE
Adds import docs for LB pools and monitors

### PR DESCRIPTION
**Pull request by riuvshyn**
Adds import docs for LB pools and monitors

I've actually tested it.

### CODE REVIEW

**Review by jacobbednarz — CHANGES_REQUESTED** [review]
While this works (due to passing through the ID and `schema.ImportStatePassthrough`) it's ambiguous as to which level of load balancer resource it should create (user, zone, account). I'm hesitant to document this as doing so as I suspect it will catch people out.

To get this over the line, we'll need to update the `Import` methods to determine which level it is using (probably by including it in the import string identifier) before attempting to import the state.

**Comment by riuvshyn** [comment]
@jacobbednarz are LB pools and monitors can be user/zone levels? from what I can see these are only account level at least  with current state of provider.
I do not see how to create zone specific LB pool or monitor, i see there is an API for user level but where that API is used?

**Comment by jacobbednarz** [comment]
Yep, the CRUD methods call the `cloudflare-go` library which use a helper method (`api.userBaseURL` https://github.com/cloudflare/cloudflare-go/blob/master/load_balancing.go#L160) checking for an attribute on the API client. The Terraform side of things set this when the `account_id` attribute is included in the provider configuration. There is a simpler notice on the registry documentation for load balancer monitors too - https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/load_balancer_monitor

**Comment by jacobbednarz** [comment]
closing due to going stale

**Pull request closed without merging**
