### PR TITLE
add cloudflare_url_normalization_settings resource

### PR DESCRIPTION
**Pull request by tamas-jozsa**
I'm marking this PR as draft, as FL Team is still working on the DELETE endpoint. I'll need to update that here once it's completed.

I used https://api.cloudflare.com/#url-normalization-properties to craft this resource. 
Even though the API schema marks `type` and `scope` params as optional, I confirm that they are required.

### CODE REVIEW

**Comment by sbfaulkner** [comment]
@tamas-jozsa any update here?

**Comment by tamas-jozsa** [comment]
@sbfaulkner development has been delayed on the API side, and I'm not sure about their ETA. I can close this PR and reopen once we move forward, if that sounds OK for you.

**Review by jafowler — APPROVED** [review]
LGTM

**Comment by jafowler** [comment]
@jacobbednarz I think this is good to go now. We had a discussion with the FL team and it looks like setting to the default value (as @tamas-jozsa has done here) is the way they want to handle the DELETE calls.

**Comment by jacobbednarz** [comment]
cool, do we have public docs yet? I'll re-run the acceptance test suite tomorrow.

**Comment by jacobbednarz** [comment]
acceptance tests all passing

```
TF_ACC=1 go test $(go list ./...) -v -run "^TestAccCloudflareURLNormalizationSettings_" -count 1 -parallel 1 -timeout 120m -parallel 1
?   	github.com/cloudflare/terraform-provider-cloudflare	[no test files]
=== RUN   TestAccCloudflareURLNormalizationSettings_CreateThenUpdate
=== PAUSE TestAccCloudflareURLNormalizationSettings_CreateThenUpdate
=== CONT  TestAccCloudflareURLNormalizationSettings_CreateThenUpdate
--- PASS: TestAccCloudflareURLNormalizationSettings_CreateThenUpdate (24.02s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/provider	24.460s
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/changelog-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/maintainer-only-file-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/tf-log-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/version	[no test files]
```

**Pull request merged**
