### PR TITLE
Use list of maps for notification filters to allow better control and validation.

### LINKED ISSUE #1189: Crashes on cloudflare_notification_policy
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.26.1

### Affected resource(s)

cloudflare_notification_policy

### Terraform configuration files

```hcl
resource cloudflare_notification_policy notif {
	account_id = var.account_id
	name = "Pool enablement"
	description = "Pool enablement"
	enabled     =  true
	alert_type  = "g6_pool_toggle_alert"

	email_integration {
		id   =  "myemail@example.com"
	}
	filters = {
		enabled = ["true", "false"]
	}
}
```

### Debug output

[log.txt](https://github.com/cloudflare/terraform-provider-cloudflare/files/7152993/log.txt)

### Panic output

_No response_

### Expected output

I expect the ressource to be created without crashing terraform

### Actual output

Plugin crashes

### Steps to reproduce

1. Copy the configuration
2. Run terraform apply

### Additional factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by broswen**
Fixes #1189 

This PR takes the changes made by 0gajun on #1520  and makes some final changes to the tests and code refactoring.

Note: I have commented out and removed the `conditions` argument due to lack of external documentation.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
thanks for the effort you've put in here however, i'm really not comfortable relying on `TypeMap`s. we had *alot* of internal issues with Terraform when using maps and we finally migrated away from them with the 3.x upgrade (see [3.x upgrade guide](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/website/docs/guides/version-3-upgrade.html.md)) and there hasn't been any changes in Terraform core that improved schema support, validation or helper methods so i'm not keen to re-introduce them for nested properties at this stage. fwiw, the nested `TypeList` or `TypeSet` actually map correctly to the API response here, `TypeMap` is a bit of munge to get it to work.

looks like there is an acceptance test failure too on the service side as well which we'll need to dig into.

```
TF_ACC=1 go test $(go list ./...) -v -run "^TestAccCloudflareNotificationPolicy_WithFiltersAttribute" -count 1 -parallel 1 -timeout 120m -parallel 1
?   	github.com/cloudflare/terraform-provider-cloudflare	[no test files]
=== RUN   TestAccCloudflareNotificationPolicy_WithFiltersAttribute
    resource_cloudflare_notification_policy_test.go:88: Step 2/2 error: Error running apply: exit status 1

        Error: error updating notification policy 084abc3c3c4e435ca7434258d9dc2952: internal service error

          with cloudflare_notification_policy.ylezvrpogw,
          on terraform_plugin_test.tf line 2, in resource "cloudflare_notification_policy" "ylezvrpogw":
           2:   resource "cloudflare_notification_policy" "ylezvrpogw" {

--- FAIL: TestAccCloudflareNotificationPolicy_WithFiltersAttribute (24.76s)
FAIL
FAIL	github.com/cloudflare/terraform-provider-cloudflare/cloudflare	25.335s
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/changelog-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/maintainer-only-file-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/tf-log-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/version	[no test files]
FAIL
make: *** [testacc] Error 1
```

**Comment by jacobbednarz** [comment]
looks like we fixed the new test but the old one is broken with what appears to be a config issue

```
TF_ACC=1 go test $(go list ./...) -v -run "^TestAccCloudflareNotificationPolicy_" -count 1 -parallel 1 -timeout 120m -parallel 1
?   	github.com/cloudflare/terraform-provider-cloudflare	[no test files]
=== RUN   TestAccCloudflareNotificationPolicy_Basic
    resource_cloudflare_notification_policy_test.go:20: Step 2/2 error: Error running apply: exit status 1

        Error: error updating notification policy 568c216d01384658b625282a093b4f96: Invalid policy condition for alert type. (17007)

          with cloudflare_notification_policy.njfvpufpld,
          on terraform_plugin_test.tf line 2, in resource "cloudflare_notification_policy" "njfvpufpld":
           2:   resource "cloudflare_notification_policy" "njfvpufpld" {

--- FAIL: TestAccCloudflareNotificationPolicy_Basic (12.81s)
=== RUN   TestAccCloudflareNotificationPolicy_WithFiltersAttribute
--- PASS: TestAccCloudflareNotificationPolicy_WithFiltersAttribute (15.69s)
FAIL
FAIL	github.com/cloudflare/terraform-provider-cloudflare/cloudflare	29.072s
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/changelog-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/maintainer-only-file-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/tf-log-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/version	[no test files]
FAIL
make: *** [testacc] Error 1
```

request
```
{
  "id": "568c216d01384658b625282a093b4f96",
  "name": "updated test SSL policy from terraform provider",
  "description": "updated description",
  "enabled": true,
  "alert_type": "universal_ssl_event_type",
  "mechanisms": {
    "email": [
      {
        "id": "test@example.com"
      }
    ]
  }
}
```

response 
```
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 17007,
      "message": "Invalid policy condition for alert type."
    }
  ],
  "messages": []
}
```

are we also able to update the `filters` documentation at https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/website/docs/r/notification_policy.html.markdown to clarify the available fields?

**Comment by broswen** [comment]
@jacobbednarz That's odd, those two acceptance tests work on my personal account. It looks like the `conditions` property needs to be set (to empty) even though it's not used for that alert type. The `buildNotificationPolicy()` function always sets that member to an empty before sending. Not sure why it is not appearing in the JSON payload.

I added more documentation as requested and pulled a bunch of alert types and filters from the dashboard.

**Comment by jacobbednarz** [comment]
we're good on the acceptance tests front, i may have been using an older cloudflare-go version 

```
TF_ACC=1 go test $(go list ./...) -v -run "^TestAccCloudflareNotificationPolicy_" -count 1 -parallel 1 -timeout 120m -parallel 1
?   	github.com/cloudflare/terraform-provider-cloudflare	[no test files]
=== RUN   TestAccCloudflareNotificationPolicy_Basic
--- PASS: TestAccCloudflareNotificationPolicy_Basic (16.69s)
=== RUN   TestAccCloudflareNotificationPolicy_WithFiltersAttribute
--- PASS: TestAccCloudflareNotificationPolicy_WithFiltersAttribute (17.63s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/cloudflare	34.827s
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/changelog-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/maintainer-only-file-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/tf-log-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/version	[no test files]
```

**Comment by jacobbednarz** [comment]
thanks for this @broswen 👏 let's get this merged and ready for the next release.

**Pull request merged**
