### PR TITLE
#2591 address browser_ttl.default value issue of not being able to be set to `0`

### PR DESCRIPTION
**Pull request by nialdaly**
### Summary
Hi there, this is a possible resolution to issue [#2591](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2591).

When the `Browser TTL` option is to set to `Override origin` and `No cache` the corresponding `default` value is `0`.

Screenshot 2023-07-06 at 22 05 11

I'm unable to run the acceptance tests locally, so any guidance would be greatly appreciated!

### CODE REVIEW

**Comment by jacobbednarz** [comment]
@iveelsm can you clarify the expected behaviour here and if this was intentional?

**Comment by iveelsm** [comment]
@jacobbednarz This was intentional. I will surface it more on the issue as well, but this is the underlying implementation leaking through here. The general problem here is that a Browser TTL of "Override Origin" set to `0` actually translates on the backend to "Respect Origin".

I have a new feature for Browser Bypass which is rolling out soon, but we should not allow people to specify `0` here until the legacy API contracts are sufficiently wrangled.

**Comment by nialdaly** [comment]
Thanks for clarifying @iveelsm

**Comment by iveelsm** [comment]
Sure thing @nialdaly! Thank you for the PR! This is just one of those unfortunate things where our API internally isn't quite as logical as we need it to be and requires a lot of backend work before this would work.

**Comment by nialdaly** [comment]
That makes sense, thanks for the additional context!

**Pull request closed without merging**
