### PR TITLE
cloudflare_spectrum_application: Remove default values, make `edge_ip…

### PR DESCRIPTION
**Pull request by Nmishin**
…s` parameter optional

### CODE REVIEW

**Comment by Nmishin** [comment]
Fix for https://github.com/cloudflare/terraform-provider-cloudflare/issues/2622

Default values deleted because they prevent users from create some different types of Spectrum applications.

For prevent errors like `json: unknown field "edge_ips`, all that parameters (`traffic_type`, `tls`, `ip_firewall`, `proxy_protocol`, `argo_smart_routing`) should be configured explicitly only for needed application types.

**Comment by jacobbednarz** [comment]
these defaults were intentionally added as the API required them at one point in time. i'll send this to the team internally to confirm what behaviour we need here vs in the Go library.

**Comment by Nmishin** [comment]
@jacobbednarz I fully agree, but we definitely need to to something with that, because for now I can't create spectrum app at all. For example, in my account available only ssh, rdp, and minecraft, and I can't create any of them because of default values (v4.10.0 provider):

```
resource "cloudflare_spectrum_application" "spectrum" {
  zone_id  = var.zone_id
  protocol = "rdp"

  dns {
    type = "CNAME"
    name = "rdp.mydomain"
  }

  origin_direct = [
    "tcp://95.163.248.95:3389"
  ]

}
```

```
terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_spectrum_application.spectrum will be created
  + resource "cloudflare_spectrum_application" "spectrum" {
      + argo_smart_routing = false
      + id                 = (known after apply)
      + ip_firewall        = true
      + origin_direct      = [
          + "tcp://95.163.248.95:3389",
        ]
      + protocol           = "rdp"
      + proxy_protocol     = "off"
      + tls                = "off"
      + traffic_type       = "direct"
      + zone_id            = "df066cb84f969ab8f4bc51b7f2eb2aa6"

      + dns {
          + name = "rdp.mydomain"
          + type = "CNAME"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_spectrum_application.spectrum: Creating...
╷
│ Error: error creating spectrum application for zone: json: unknown field "traffic_type" (10012)
│ 
│   with cloudflare_spectrum_application.spectrum,
│   on main.tf line 1, in resource "cloudflare_spectrum_application" "spectrum":
│    1: resource "cloudflare_spectrum_application" "spectrum" {
```

**Comment by jacobbednarz** [comment]
this PR is on hold as we've found the zone mentioned in the original issue isn't correctly setup which may be the cause here.

**Comment by aberglund-cf** [comment]
Hi @Nmishin, I've tested this PR and while it does fix the problem in the issue it still has some slightly strange behavior regarding the change to default values. 

I'm seeing that when `edge_ips` is not declared it will always show a diff trying to remove those elements:
```shell
~ resource "cloudflare_spectrum_application" "testapp" {
        id                 = "<id>"
      - proxy_protocol     = "off" -> null
      - tls                = "off" -> null
      - traffic_type       = "direct" -> null
        # (5 unchanged attributes hidden)

      - edge_ips {
          - connectivity = "all" -> null
          - ips          = [] -> null
          - type         = "dynamic" -> null
        }

        # (2 unchanged blocks hidden)
    }
```
I believe this is due to the mismatched handling of default values between the provider and the API. The API is returning the default values but the provider isn't expecting them and will try to remove those values. Ideally we'd want to avoid this confusing behavior. I think a good approach would be keep your change for reading `edge_ips` config values and to align the defaults values in the schema with what's being produced by the API.

Maybe the `edge_ips` schema can be updated to show something like this?
```go
"edge_ips": {
       Type:     schema.TypeList,
       Optional: true,
       Computed: true,
       DefaultFunc: func() (interface{}, error) {
               defaults := map[string]interface{}{
                       "type":         cloudflare.SpectrumEdgeTypeDynamic,
                       "connectivity": cloudflare.SpectrumConnectivityAll,
                       "ips":          []string{},
               }
               return []map[string]interface{}{defaults}, nil
       },
       MaxItems:    1,
```
Please let us know if this helps with your issue.

**Comment by Nmishin** [comment]
Hi @aberglund-cf could you please check/test my MR for now, because i don't have all config options in my subscription ...
I added "Computed: true" option to the properties, and as I can read, this can be enough for handle default values from API.
If it still work incorrectly - please fell free to add commits to my MR :)

**Comment by jacobbednarz** [comment]
this looks good from an acceptance test perspective

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareSpectrumApplication_" -count 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareSpectrumApplication_Basic
--- PASS: TestAccCloudflareSpectrumApplication_Basic (12.56s)
=== RUN   TestAccCloudflareSpectrumApplication_OriginDNS
--- PASS: TestAccCloudflareSpectrumApplication_OriginDNS (10.67s)
=== RUN   TestAccCloudflareSpectrumApplication_OriginPortRange
--- PASS: TestAccCloudflareSpectrumApplication_OriginPortRange (13.06s)
=== RUN   TestAccCloudflareSpectrumApplication_Update
--- PASS: TestAccCloudflareSpectrumApplication_Update (18.40s)
=== RUN   TestAccCloudflareSpectrumApplication_EdgeIPConnectivity
--- PASS: TestAccCloudflareSpectrumApplication_EdgeIPConnectivity (10.95s)
=== RUN   TestAccCloudflareSpectrumApplication_EdgeIPsMultiple
--- PASS: TestAccCloudflareSpectrumApplication_EdgeIPsMultiple (13.84s)
=== RUN   TestAccCloudflareSpectrumApplication_BasicSSH
--- PASS: TestAccCloudflareSpectrumApplication_BasicSSH (9.82s)
=== RUN   TestAccCloudflareSpectrumApplication_BasicRDP
--- PASS: TestAccCloudflareSpectrumApplication_BasicRDP (9.08s)
=== RUN   TestAccCloudflareSpectrumApplication_BasicMinecraft
--- PASS: TestAccCloudflareSpectrumApplication_BasicMinecraft (9.40s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	108.788s
```

once @aberglund-cf gives the 👍 , we can merge.

@Nmishin in the meantime, can you please run `make docs` to have the documentation update correctly?

**Review by aberglund-cf — COMMENTED** [review]
:+1:  LGTM. Thanks for helping us sort out this issue!

**Pull request merged**
