### PR TITLE
Add r2_bucket_binding to cloudflare_worker_script

### PR DESCRIPTION
**Pull request by yonran**
Add support for adding r2 bucket bindings to a `cloudflare_worker_script`. This is part of https://github.com/cloudflare/terraform-provider-cloudflare/issues/1664

The new block `r2_bucket_binding` within a `cloudflare_worker_script` allows you to bind an r2 bucket to a worker script. Each binding becomes a global variable within the worker script (`cloudflare_worker_script` does not support creating a worker with format: module yet).

No tests yet since [cloudflare-go](https://github.com/cloudflare/cloudflare-go) does not yet support creating r2 buckets.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
thanks @yonran; can you please add acceptance test coverage for this new feature?

**Comment by jacobbednarz** [comment]
> No tests yet since [cloudflare-go](https://github.com/cloudflare/cloudflare-go) does not yet support creating r2 buckets.

you were about 3 hours too quick 😉 cloudflare/cloudflare-go#1028 added support for R2 bucket creation and deletion.

**Comment by yonran** [comment]
> thanks @yonran; can you please add acceptance test coverage for this new feature?

@jacobbednarz,  I tried to update the acceptance test. As [cloudflare-go 0.47.0](https://github.com/cloudflare/cloudflare-go/blob/master/CHANGELOG.md#0470-unreleased), has not been released yet, compiling requires you to upgrade to master (`go get github.com/cloudflare/cloudflare-go@master`) or to override to master (`go mod edit -replace github.com/cloudflare/cloudflare-go=github.com/cloudflare/cloudflare-go@master`)

However, I am running into a problem that the [create bucket API](https://api.cloudflare.com/#r2-bucket-create-bucket) does not seem to be working for me; when I try to `POST https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/r2/buckets/mytest`, it returns HTTP status 404 with message “No route matches this url.” The same thing happens when I try to run `npx wrangler r2 bucket create mytest`, which [calls PUT](https://github.com/cloudflare/wrangler2/blob/db592f09de62d385f440d8aa38e09d01f10fca11/packages/wrangler/src/r2.ts#L32-L40) instead of POST.

**Comment by Cyb3r-Jak3** [comment]
@yonran Looks like R2 had a change https://github.com/cloudflare/cloudflare-go/issues/1033. Waiting on R2 team response's before patching.

**Comment by yonran** [comment]
Now that CloudFlare has fixed the create bucket api (https://github.com/cloudflare/wrangler2/issues/1654#issuecomment-1215236099), my acceptance test passes against cloudflare-go master. Still waiting on cloudflare-go to release 0.47.0 though.

```
TF_ACC=1 CLOUDFLARE_EMAIL=yonathan@gmail.com CLOUDFLARE_API_KEY=… CLOUDFLARE_DOMAIN=… CLOUDFLARE_ZONE_ID=… CLOUDFLARE_ACCOUNT_ID=… go test github.com/cloudflare/terraform-provider-cloudflare/internal/provider -run TestAccCloudflareWorkerScript_MultiScriptEnt
```

**Comment by yonran** [comment]
[cloudflare-go@0.47.0](https://github.com/cloudflare/cloudflare-go/blob/master/CHANGELOG.md#0470-august-17th-2022) has been released but it contained a number of minor breaking changes and an accidental regression to `CreateZoneLockdown` (lost the `Priority` field). So now we have to wait for [cloudflare-go@0.48.0](https://github.com/cloudflare/cloudflare-go/blob/master/CHANGELOG.md#0480-unreleased)

**Comment by jacobbednarz** [comment]
v0.47.1 was released to address that specific issue.

**Comment by jacobbednarz** [comment]
I'll bump the library version in another PR and we can pull it in here once it is ready.

**Comment by yonran** [comment]
Thanks @jacobbednarz for merging the cloudflare-go upgrade! Do you want any other fixes or rebases on this PR?

**Comment by jacobbednarz** [comment]
nothing more from you; i just ran out of time to run the acceptance test suite last week. the API for the R2 bucket create has (hopefully, 🤞 ) stabilised with cloudflare/cloudflare-go#1035 and i'm cutting a release now for that and another API issue. aiming to get this sorted today.

**Comment by jacobbednarz** [comment]
acceptance tests are green

```
TF_ACC=1 go test $(go list ./...) -v -run "^TestAccCloudflareWorkerScript_" -count 1 -parallel 1 -timeout 120m -parallel 1
?       github.com/cloudflare/terraform-provider-cloudflare     [no test files]
=== RUN   TestAccCloudflareWorkerScript_Import
--- PASS: TestAccCloudflareWorkerScript_Import (14.94s)
=== RUN   TestAccCloudflareWorkerScript_MultiScriptEnt
=== PAUSE TestAccCloudflareWorkerScript_MultiScriptEnt
=== CONT  TestAccCloudflareWorkerScript_MultiScriptEnt
--- PASS: TestAccCloudflareWorkerScript_MultiScriptEnt (36.51s)
PASS
ok      github.com/cloudflare/terraform-provider-cloudflare/internal/provider   52.039s
?       github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/changelog-check   [no test files]
?       github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/maintainer-only-file-check        [no test files]
?       github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/tf-log-check      [no test files]
?       github.com/cloudflare/terraform-provider-cloudflare/version     [no test files]
```

**Comment by jacobbednarz** [comment]
thanks for the persistence here @yonran, this is great 🥇

**Pull request merged**
