### PR TITLE
[WIP] Add hyperdrive_config_binding to Cloudflare Workers

### PR DESCRIPTION
**Pull request by OilyLime**

### CODE REVIEW

**Comment by OilyLime** [comment]
Hey @jacobbednarz, like we discussed, can you help me get the Hyperdrive config IDs to this PR so that we can get the tests passing and push this guy through?

**Comment by jacobbednarz** [comment]
i've got ahead and dropped the secrets in place for the tests to start using - https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/.github/workflows/acceptance-tests.yml#L44-L48

we'll need to remove the version bumps from this PR to have it apply cleanly though.

**Comment by jacobbednarz** [comment]
hyperdrive ID is `fb071427ce3740d8bc2948776cc646a7`

**Comment by jacobbednarz** [comment]
acceptance tests all passing

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareWorkerScript_" -count 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareWorkerScript_Import
--- PASS: TestAccCloudflareWorkerScript_Import (5.49s)
=== RUN   TestAccCloudflareWorkerScript_MultiScriptEnt
=== PAUSE TestAccCloudflareWorkerScript_MultiScriptEnt
=== RUN   TestAccCloudflareWorkerScript_ModuleUpload
=== PAUSE TestAccCloudflareWorkerScript_ModuleUpload
=== CONT  TestAccCloudflareWorkerScript_MultiScriptEnt
--- PASS: TestAccCloudflareWorkerScript_MultiScriptEnt (20.22s)
=== CONT  TestAccCloudflareWorkerScript_ModuleUpload
--- PASS: TestAccCloudflareWorkerScript_ModuleUpload (12.81s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	39.550s
```

**Pull request merged**
