### PR TITLE
resource/cloudflare_access_application: add type=private_ip

### PR DESCRIPTION
**Pull request by csautter**
Quick Fix for Issue

Closes https://github.com/cloudflare/terraform-provider-cloudflare/issues/1974

### CODE REVIEW

**Comment by jacobbednarz** [comment]
@csautter to get this over the line, you'll need to:

- address the inline comments
- add a CHANGELOG entry (see comment above)
- run `make docs` locally to update the generated registry documentation (see https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md)

**Comment by jacobbednarz** [comment]
@Justin-Holmes do we have this in the backlog to be documented publicly?

**Comment by Justin-Holmes** [comment]
> @Justin-Holmes do we have this in the backlog to be documented publicly?

Unfortunately, we don't have plans on adding private apps to the API docs because they're considered unstable at the moment. We'll be doing work on private apps in the coming months and we'll publicly document after that work is complete!

**Comment by jacobbednarz** [comment]
thanks! closing this out in the meantime while unstable.

**Comment by F21** [comment]
Sorry for bumping up a closed issue, but is the private apps api considered stable now? They aren't labeled as beta in the zero trust UI and seem to be well documented here: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/private-net/connect-private-networks/

**Comment by itsmechlark** [comment]
@jacobbednarz , any news? Is this possible to get release so we can provision access apps for private ips.

**Comment by kurochan** [comment]
I am looking forward to it as well.

**Comment by bipbipbipbipbip** [comment]
@jacobbednarz it has been a more than a year since this PR was opened. As far as we can tell the API is considered stable, so when could we expect an update on these resources?

**Comment by derence-boxed** [comment]
Is it possible to add this type to the resource cloudflare_access_application? face the same situation here as well

**Comment by nlkaisert** [comment]
@jacobbednarz @Justin-Holmes is the API considered stable now? The type seems to still be missing from the cloudflare_access_application, but when using the cf-terraforming tool, then it gets generated with the type "private_ip". This is highly confusing. Is this scenario supported or not?

**Pull request closed without merging**
