### PR TITLE
resource/cloudflare_zone_settings_override: add more supported properties

### LINKED ISSUE #1165: Add zone setting for `orange_to_orange`
### Current Terraform and Cloudflare provider version

Terraform 1.0
provider - dev

### Description

Add support for `orange_to_orange` as a zone setting

### Use cases

Manage `orange_to_orange` for zones

### Potential Terraform configuration

```hcl
resource "cloudflare_zone_setting" "" {
  # ...
  settings {
    orange_to_orange = "on"
  }
}
```

### References

https://api.cloudflare.com/#zone-settings-get-orange-to-orange-o2o-
https://api.cloudflare.com/#zone-settings-change-orange-to-orange-o2o-

### PR DESCRIPTION
**Pull request by jacobbednarz**
- `binary_ast`
- `filter_logs_to_cloudflare`
- `log_to_cloudflare`
- `orange_to_orange`
- `visitor_ip`
- `proxy_read_timeout`

Closes #1165

### CODE REVIEW

**Comment by alex-feel** [comment]
Hi guys, it looks like `binary_ast` [is no longer supported](https://community.cloudflare.com/t/solved-binaryast-availability-depending-on-plan/337044). Shouldn't it be removed?

**Comment by alex-feel** [comment]
It also looks like `proxy_read_timeout` setting is not a string type according to the [docs](https://api.cloudflare.com/#zone-settings-change-proxy-read-timeout-setting).

**Comment by alex-feel** [comment]
@Nuxij I didn't fork this repo, I didn't work on it, so I can't make a PR. I'm only working on this module: https://github.com/alex-feel/terraform-cloudflare-zone, not the provider itself.

**Comment by alex-feel** [comment]
@Nuxij I didn't fork this repo, I didn't work on it, so I can't make a PR. I'm only working on this module: https://github.com/alex-feel/terraform-cloudflare-zone, rather than on the provider itself.

**Comment by Nuxij** [comment]
Oh sorry I misunderstood what your repo was! Should I switch to that module for an easier time?

**Comment by alex-feel** [comment]
Of course you decide, but I would try in your place) I can only add that I myself use this module in my work tasks.

**Pull request merged**
