### PR TITLE
Add non_identity_browser_isolation_enabled field in Browser Isolation…

### PR DESCRIPTION
**Pull request by pierreca**
… settings

- Update to cloudflare/cloudflare-go v0.80.0
- Update Browser Isolation settings to reflect the breaking change and the new field

### CODE REVIEW

**Comment by pierreca** [comment]
@jacobbednarz i'm not used to modifying the terraform provider, I have no idea if this constitutes a complete change or if something else is needed.

**Comment by jacobbednarz** [comment]
yep, we want a changelog here. however, as the automation mentions, we want to remove the version bump commit. we have automation that handles that outside of PRs to prevent merge conflict hell.

**Comment by pierreca** [comment]
I've removed the version bump, I'm assuming the unit test will succeed when rebased on a commit that includes the version bump.
this being said, i'm not sure if those two modifications are the only things needed to enable these features or if I miss a piece of code somewhere else?

**Comment by jacobbednarz** [comment]
acceptance tests all looking good

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^(TestAccCloudflareAccessPolicy_|TestAccCloudflareTeamsAccounts_)" -count 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareAccessPolicy_ServiceToken
--- PASS: TestAccCloudflareAccessPolicy_ServiceToken (13.36s)
=== RUN   TestAccCloudflareAccessPolicy_AnyServiceToken
--- PASS: TestAccCloudflareAccessPolicy_AnyServiceToken (12.65s)
=== RUN   TestAccCloudflareAccessPolicy_WithZoneID
--- PASS: TestAccCloudflareAccessPolicy_WithZoneID (20.41s)
=== RUN   TestAccCloudflareAccessPolicy_Group
--- PASS: TestAccCloudflareAccessPolicy_Group (16.19s)
=== RUN   TestAccCloudflareAccessPolicy_MTLS
--- PASS: TestAccCloudflareAccessPolicy_MTLS (12.08s)
=== RUN   TestAccCloudflareAccessPolicy_CommonName
--- PASS: TestAccCloudflareAccessPolicy_CommonName (12.39s)
=== RUN   TestAccCloudflareAccessPolicy_EmailDomain
--- PASS: TestAccCloudflareAccessPolicy_EmailDomain (12.30s)
=== RUN   TestAccCloudflareAccessPolicy_Emails
--- PASS: TestAccCloudflareAccessPolicy_Emails (11.96s)
=== RUN   TestAccCloudflareAccessPolicy_Everyone
--- PASS: TestAccCloudflareAccessPolicy_Everyone (11.82s)
=== RUN   TestAccCloudflareAccessPolicy_IPs
--- PASS: TestAccCloudflareAccessPolicy_IPs (12.15s)
=== RUN   TestAccCloudflareAccessPolicy_AuthMethod
--- PASS: TestAccCloudflareAccessPolicy_AuthMethod (12.48s)
=== RUN   TestAccCloudflareAccessPolicy_Geo
--- PASS: TestAccCloudflareAccessPolicy_Geo (11.94s)
=== RUN   TestAccCloudflareAccessPolicy_Okta
--- PASS: TestAccCloudflareAccessPolicy_Okta (11.81s)
=== RUN   TestAccCloudflareAccessPolicy_PurposeJustification
--- PASS: TestAccCloudflareAccessPolicy_PurposeJustification (15.08s)
=== RUN   TestAccCloudflareAccessPolicy_ApprovalGroup
--- PASS: TestAccCloudflareAccessPolicy_ApprovalGroup (13.50s)
=== RUN   TestAccCloudflareAccessPolicy_ExternalEvaluation
--- PASS: TestAccCloudflareAccessPolicy_ExternalEvaluation (12.21s)
=== RUN   TestAccCloudflareAccessPolicy_IsolationRequired
--- PASS: TestAccCloudflareAccessPolicy_IsolationRequired (17.54s)
=== RUN   TestAccCloudflareTeamsAccounts_ConfigurationBasic
--- PASS: TestAccCloudflareTeamsAccounts_ConfigurationBasic (12.29s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	242.709s
```

**Pull request merged**
