### PR TITLE
Add tunnel_protocol field for device policies

### PR DESCRIPTION
**Pull request by jlu-cloudflare**
Depends on https://github.com/cloudflare/cloudflare-go/pull/2778

### CODE REVIEW

**Comment by jacobbednarz** [comment]
looks like there is an assertion failure here

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareDeviceSettingsPolicy_" -count 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareDeviceSettingsPolicy_Create
    resource_cloudflare_device_settings_policy_test.go:31: Step 1/3 error: Check failed: Check 19/19 error: cloudflare_device_settings_policy.hmxrmjxwvv: Attribute 'tunnel_protocol' expected "wireguard", got ""
--- FAIL: TestAccCloudflareDeviceSettingsPolicy_Create (3.50s)
FAIL
FAIL	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	3.909s
FAIL
make: *** [testacc] Error 1
```

**Comment by jlu-cloudflare** [comment]
> looks like there is an assertion failure here

This seems to be passing for me locally 🤔 
Any tips as to how I could repro this locally?

**Comment by jacobbednarz** [comment]
i can't think of anything outside of the usual account entitlements, etc. however, to confirm you are running the acceptance test suite? not just the unit tests (command is in the output just in case)?

**Comment by jlu-cloudflare** [comment]
I was not running the acceptance test 😅 
Worked with a teammate to push up changes that seem to have addressed the issue though!

**Comment by jacobbednarz** [comment]
nice one! acceptance tests all passing

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareDeviceSettingsPolicy_" -count 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareDeviceSettingsPolicy_Create
--- PASS: TestAccCloudflareDeviceSettingsPolicy_Create (6.36s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	7.894s
```

**Pull request merged**
