### PR TITLE
R2 bucket

### LINKED ISSUE #1664: Resources for managing R2
### Current Terraform and Cloudflare provider version

N/A

### Description

Would be nice to have resources for managing [R2](https://developers.cloudflare.com/r2/) buckets.

### Use cases

To manage everything in Terraform.

### Potential Terraform configuration

Something similar to the [aws_s3_bucket](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket) and the related resources.

### References

_No response_

### PR DESCRIPTION
**Pull request by Cyb3r-Jak3**
Adds basic management for R2 buckets. 

Closes #1664.

### CODE REVIEW

**Comment by Cyb3r-Jak3** [comment]
Needs https://github.com/cloudflare/cloudflare-go/pull/1265

**Comment by Cyb3r-Jak3** [comment]
Should be good once https://github.com/cloudflare/terraform-provider-cloudflare/pull/2466 is merged.

**Comment by jacobbednarz** [comment]
acceptance tests all passing

```
TF_ACC=1 go test ./internal/framework/service/r2_bucket -v -count 1 -run ^TestAccCloudflareR2Bucket_ -timeout 120m -parallel 1
=== RUN   TestAccCloudflareR2Bucket_Basic
=== PAUSE TestAccCloudflareR2Bucket_Basic
=== RUN   TestAccCloudflareR2Bucket_Minimum
=== PAUSE TestAccCloudflareR2Bucket_Minimum
=== CONT  TestAccCloudflareR2Bucket_Basic
--- PASS: TestAccCloudflareR2Bucket_Basic (20.84s)
=== CONT  TestAccCloudflareR2Bucket_Minimum
--- PASS: TestAccCloudflareR2Bucket_Minimum (16.78s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/r2_bucket	38.431s
```

**Comment by jacobbednarz** [comment]
i've also updated this PR to close #1664 as we don't want laundry list support issues. instead, we want specific issues that cover each part that can be tackled separately. the OP in the attached issue was after bucket support which we are adding here.

**Pull request merged**
