### PR TITLE
Add rate limiting match response headers

### PR DESCRIPTION
**Pull request by vync**
Addresses #196  

I have run make tests and they do succeed and I am happy to put in some integration tests if provided with some guidance. Please review.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Thanks for putting this together @vync! We appreciate it. We will require tests for this change before it can land in order to prevent any future regressions of this functionality. Check out Terraform's documentation on adding acceptance tests (https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html) or have a flick through some of the existing ones in this repository.

**Comment by jacobbednarz** [comment]
The two updated tests have caused panics.

```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccCloudflareRateLimit_FullySpecified
=== PAUSE TestAccCloudflareRateLimit_FullySpecified
=== CONT  TestAccCloudflareRateLimit_FullySpecified

------- Stderr: -------
panic: interface conversion: interface {} is map[string]interface {}, not cloudflare.RateLimitResponseMatcherHeader

goroutine 94 [running]:
github.com/terraform-providers/terraform-provider-cloudflare/cloudflare.expandRateLimitTrafficMatcher(0xc000121ce0, 0xc00018a300, 0x6, 0x6, 0xc000493fa0, 0x2, 0x2, 0xc000796210, 0x29, 0x0, ...)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/cloudflare/resource_cloudflare_rate_limit.go:377 +0xa0f
github.com/terraform-providers/terraform-provider-cloudflare/cloudflare.resourceCloudflareRateLimitCreate(0xc000121ce0, 0x13c0a60, 0xc000108a80, 0x2, 0x225d640)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/cloudflare/resource_cloudflare_rate_limit.go:232 +0x215
github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00046a280, 0xc000442eb0, 0xc0002df100, 0x13c0a60, 0xc000108a80, 0xc000198901, 0xc000269f10, 0x1204900)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:305 +0x3b4
github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00046ac80, 0xc000213a68, 0xc000442eb0, 0xc0002df100, 0xc00014a748, 0xc000438748, 0x1207300)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x18f
github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000438310, 0x1739f60, 0xc000775770, 0xc000517920, 0xc000438310, 0xc000775770, 0xc000559bd0)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x884
github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1378e20, 0xc000438310, 0x1739f60, 0xc000775770, 0xc0005178c0, 0x0, 0x1739f60, 0xc000775770, 0xc00060d900, 0x48a)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x23e
github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005b02c0, 0x1749c20, 0xc00040d680, 0xc00010a500, 0xc0003922a0, 0x2230840, 0x0, 0x0, 0x0)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:995 +0x466
github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0005b02c0, 0x1749c20, 0xc00040d680, 0xc00010a500, 0x0)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:1275 +0xda6
github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00054c040, 0xc0005b02c0, 0x1749c20, 0xc00040d680, 0xc00010a500)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:710 +0x9f
created by github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:708 +0xa1
```

```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccCloudflareRateLimit_Update
=== PAUSE TestAccCloudflareRateLimit_Update
=== CONT  TestAccCloudflareRateLimit_Update

------- Stderr: -------
panic: interface conversion: interface {} is map[string]interface {}, not cloudflare.RateLimitResponseMatcherHeader

goroutine 365 [running]:
github.com/terraform-providers/terraform-provider-cloudflare/cloudflare.expandRateLimitTrafficMatcher(0xc00058f500, 0xc0008daba0, 0x6, 0x6, 0xc0004ac180, 0x2, 0x2, 0xc000b063f0, 0x29, 0x0, ...)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/cloudflare/resource_cloudflare_rate_limit.go:377 +0xa0f
github.com/terraform-providers/terraform-provider-cloudflare/cloudflare.resourceCloudflareRateLimitUpdate(0xc00058f500, 0x13c0a60, 0xc00039c900, 0x24, 0x225d640)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/cloudflare/resource_cloudflare_rate_limit.go:299 +0x2b4
github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00047e280, 0xc00029b310, 0xc000215760, 0x13c0a60, 0xc00039c900, 0xc000256801, 0xc00009a958, 0x1204900)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:311 +0x264
github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00047ec80, 0xc0003b7a68, 0xc00029b310, 0xc000215760, 0xc0002db928, 0xc000010901, 0x1207300)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x18f
github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000442500, 0x1739f60, 0xc0006ebaa0, 0xc0004c9380, 0xc000442500, 0xc0006ebaa0, 0xc0008f4bd0)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x884
github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1378e20, 0xc000442500, 0x1739f60, 0xc0006ebaa0, 0xc0004c9320, 0x0, 0x1739f60, 0xc0006ebaa0, 0xc0004e5100, 0x608)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x23e
github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003c18c0, 0x1749c20, 0xc0006f9680, 0xc000014c00, 0xc0008c8cf0, 0x2230840, 0x0, 0x0, 0x0)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:995 +0x466
github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0003c18c0, 0x1749c20, 0xc0006f9680, 0xc000014c00, 0x0)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:1275 +0xda6
github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000590000, 0xc0003c18c0, 0x1749c20, 0xc0006f9680, 0xc000014c00)
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:710 +0x9f
created by github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
  $WORK_DIR/962a4ee8807683e3/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:708 +0xa1
```

You can run these locally and they replicate as in integration.

**Comment by vync-SB** [comment]
Thank you, I was working on it yesterday. More to come.

**Comment by vync-SB** [comment]
Still WIP, as tests are still breaking.

**Comment by jacobbednarz** [comment]
hey @vync-SB, where is this one at? are you still working on it?

**Comment by jacobbednarz** [comment]
Closing due to having no activity for over 30 days.

**Pull request closed without merging**
