### PR TITLE
WDAPI-645 add a device posture integration

### PR DESCRIPTION
**Pull request by aplunk**
Depends on: https://github.com/cloudflare/cloudflare-go/pull/749
This PR adds support for the device posture integration APIs.
Testing is difficult because the third party integrations require special account configuration. Please advise on the best way to integrate this into CI.

### CODE REVIEW

**Comment by aplunk** [comment]
Tests are failing pending the library update.

**Review by patryk — CHANGES_REQUESTED** [review]
Missing documentation, tests failing.

**Comment by aplunk** [comment]
> Missing documentation, tests failing.

Thanks for the review, I will update documentation. Regarding failing tests, to run these tests one would need an account with the third party service workspace one. Is there a good way to contribute a test which does not require access to a third party api?

**Review by patryk — APPROVED** [review]

**Comment by patryk** [comment]
Thanks!

**Pull request merged**
