### PR TITLE
Fix 'edge_ip_connectivity' state persistence

### LINKED ISSUE #1500: Spectrum App resource not reading "edge_ips" correctly from API
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

## Terraform
Terraform v1.1.7
    on linux_amd64

## CF Provider
3.9.10

### Affected resource(s)

cloudflare_spectrum_application

### Terraform configuration files

```hcl
resource "cloudflare_spectrum_application" "my-sfe" {
  edge_ip_connectivity = "ipv4"
  ip_firewall    = true
  origin_port    = 25
  protocol       = "tcp/25"
  proxy_protocol = "v1"
  tls            = "off"
  traffic_type   = "direct"
  zone_id        = "--REDACTED--"
  dns {
    name = "--REDACTED--"
    type = "CNAME"
  }
  origin_dns {
    name = "--REDACTED--"
  }
}
```

### Debug output
```
cloudflare_spectrum_application.my-sfe: Refreshing state... [id=--REDACTED--]
2022-03-09T17:18:31.819-0600 [INFO]  provider.terraform-provider-cloudflare_v3.10.0: 2022/03/09 17:18:31 [DEBUG] Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
GET /client/v4/zones/--REDACTED--/spectrum/apps/--REDACTED-- HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.1.7 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.10.0
Authorization: [redacted]
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------: timestamp=2022-03-09T17:18:31.819-0600
2022-03-09T17:18:32.045-0600 [INFO]  provider.terraform-provider-cloudflare_v3.10.0: 2022/03/09 17:18:32 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Cf-Cache-Status: DYNAMIC
Cf-Ray: 6e9787c13cbcd272-DFW
Content-Type: application/json; charset=UTF-8
Date: Wed, 09 Mar 2022 23:18:32 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cflb=---REDACTED--; SameSite=Lax; path=/; expires=Thu, 10-Mar-22 01:48:33 GMT; HttpOnly
Set-Cookie: __cfruid=edge_ip_connectivity-1646867912; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 41


{
  "result": {
    "id": "--REDACTED--",
    "protocol": "tcp/25",
    "dns": {
      "type": "CNAME",
      "name": "--REDACTED--"
    },
    "origin_dns": {
      "name": "--REDACTED--"
    },
    "origin_port": 25,
    "ip_firewall": true,
    "proxy_protocol": "v1",
    "tls": "off",
    "traffic_type": "direct",
    "edge_ips": {
      "type": "dynamic",
      "connectivity": "ipv4"
    },
    "created_on": "2022-02-23T19:18:35.657717Z",
    "modified_on": "2022-03-03T21:05:41.902508Z"
  },
  "success": true,
  "errors": [],
  "messages": []
}


-----------------------------------------------------: timestamp=2022-03-09T17:18:32.045-0600
2022-03-09T17:18:32.049-0600 [WARN]  Provider "registry.terraform.io/cloudflare/cloudflare" produced an invalid plan for cloudflare_spectrum_application.my-sfe, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .argo_smart_routing: planned value cty.False for a non-computed attribute
      - .edge_ips: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
2022-03-09T17:18:32.050-0600 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-03-09T17:18:32.051-0600 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.10.0/linux_amd64/terraform-provider-cloudflare_v3.10.0 pid=22776
2022-03-09T17:18:32.051-0600 [DEBUG] provider: plugin exited
2022-03-09T17:18:32.069-0600 [INFO]  backend/local: plan operation completed


Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place


Terraform will perform the following actions:


  # cloudflare_spectrum_application.my-sfe will be updated in-place
  ~ resource "cloudflare_spectrum_application" "my-sfe" {
      + edge_ip_connectivity = "ipv4"
        id                   = "--REDACTED--"
        # (9 unchanged attributes hidden)




        # (2 unchanged blocks hidden)
    }


Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as
│ part of an error message.
╵


──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
```
### Panic output

_No response_

### Expected output

I'm expecting terraform to show 0 changes since the API response shows that the edge_connectivity_type is ipv4.

```

{
  "result": {
    "id": "--REDACTED--",
    "protocol": "tcp/25",
    "dns": {
      "type": "CNAME",
      "name": "--REDACTED--"
    },
    "origin_dns": {
      "name": "--REDACTED--"
    },
    "origin_port": 25,
    "ip_firewall": true,
    "proxy_protocol": "v1",
    "tls": "off",
    "traffic_type": "direct",
    "edge_ips": {
      "type": "dynamic",
      "connectivity": "ipv4"
    },
    "created_on": "2022-02-23T19:18:35.657717Z",
    "modified_on": "2022-03-03T21:05:41.902508Z"
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

### Actual output

```
  ~ resource "cloudflare_spectrum_application" "my-sfe" {
      + edge_ip_connectivity = "ipv4"
        id                   = "--REDACTED--"
        # (9 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }
```

### Steps to reproduce

1. Create a spectrum application with a edge ip connectivity set to IPv4 and using CNAME DNS
2. Import and run a plan

### Additional factoids

In the provider, it always assumes edge_ips is a list of static IPs. It can be, but only if the connectivity type is static.

https://github.com/cloudflare/terraform-provider-cloudflare/blob/f22e8293c8317dd0b5542c3dd9e5b2fc39133e0d/cloudflare/schema_cloudflare_spectrum_application.go#L119-L131

The API uses edge_ips for setting "edge_ip_connectivity" too. This means that the edge_ip_connectivity flag doesnt get used when the provider makes a request.

Another example,

https://github.com/cloudflare/terraform-provider-cloudflare/blob/f22e8293c8317dd0b5542c3dd9e5b2fc39133e0d/cloudflare/resource_cloudflare_spectrum_application.go#L274-L286

When reading the response from the API, it looks for "edge_ip_connectivity" instead of checking in edge_ip 

### References

_No response_

### PR DESCRIPTION
**Pull request by kireledan**
Fixes #1500 

This PR fixes the `edge_ip_connectivity` value from not being stored in the terraform state when being read. 

Tested with the resource below and was able to get a `No changes` after applying and running another plan. As well as after importing the resource. 
```
resource "cloudflare_spectrum_application" "myapp-east-sfe" {
  ip_firewall    = true
  origin_port    = 25
  protocol       = "tcp/25"
  proxy_protocol = "v1"
  tls            = "off"
  traffic_type   = "direct"
  edge_ip_connectivity = "ipv4"
  zone_id        = "redacted"
  dns {
    name = "myapp-test-spectrum.redacted.net"
    type = "CNAME"
  }
  origin_dns {
    name = "myapp-test-spectrum.redacted.net"
  }
}
```

### CODE REVIEW

**Review by jacobbednarz — CHANGES_REQUESTED** [review]
you’ll need to rename the CHANGELOG file to match the PR number. 

can you please extend a test case to cover this field being saved to state? https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_spectrum_application_test.go has examples to get you started.

**Comment by kireledan** [comment]
Ah gotcha! Thought it was the Issue number. 

Ill add that test in too :+1:

**Comment by jacobbednarz** [comment]
acceptance tests are passing locally

```
TF_ACC=1 go test $(go list ./...) -v -run "^TestAccCloudflareSpectrumApplication_" -count 1 -parallel 1 -timeout 120m -parallel 1
?   	github.com/cloudflare/terraform-provider-cloudflare	[no test files]
=== RUN   TestAccCloudflareSpectrumApplication_Import
=== PAUSE TestAccCloudflareSpectrumApplication_Import
=== RUN   TestAccCloudflareSpectrumApplication_Basic
--- PASS: TestAccCloudflareSpectrumApplication_Basic (13.27s)
=== RUN   TestAccCloudflareSpectrumApplication_OriginDNS
--- PASS: TestAccCloudflareSpectrumApplication_OriginDNS (11.70s)
=== RUN   TestAccCloudflareSpectrumApplication_OriginPortRange
--- PASS: TestAccCloudflareSpectrumApplication_OriginPortRange (11.55s)
=== RUN   TestAccCloudflareSpectrumApplication_Update
--- PASS: TestAccCloudflareSpectrumApplication_Update (20.26s)
=== RUN   TestAccCloudflareSpectrumApplication_CreateAfterManualDestroy
--- PASS: TestAccCloudflareSpectrumApplication_CreateAfterManualDestroy (23.64s)
=== RUN   TestAccCloudflareSpectrumApplication_EdgeIPConnectivity
--- PASS: TestAccCloudflareSpectrumApplication_EdgeIPConnectivity (11.32s)
=== CONT  TestAccCloudflareSpectrumApplication_Import
--- PASS: TestAccCloudflareSpectrumApplication_Import (15.29s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/cloudflare	107.439s
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/changelog-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/maintainer-only-file-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/tf-log-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/version	[no test files]
```

**Comment by jacobbednarz** [comment]
thank you @kireledan for this one!

**Pull request merged**
