### PR TITLE
Add valid values to cloudflare_turnstile_widget.mode doc

### LINKED ISSUE #2417: Turnstile `mode` valid values not documented
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```text
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.5.0
+ provider registry.terraform.io/hashicorp/aws v4.62.0
```

### Affected resource(s)

- `cloudflare_turnstile_widget`

### Terraform configuration files

```hcl
resource "cloudflare_turnstile_widget" "loco_client" {
  account_id = "xxxxxxxxxxxxx"
  name       = "My thing"
  domains    = ["example.com"]

  mode = ?????
}
```

### Link to debug output

n/a

### Panic output

_No response_

### Expected output

I expected to be able to read in the documentation which values are supported for the `mode` value.

### Actual output

It's not documented.

### Steps to reproduce

1. https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/turnstile_widget#mode
2. Observe missing documentation

### Additional factoids

_No response_

### References

https://developers.cloudflare.com/api/operations/accounts-turnstile-widget-create#request-body

Seems like the valid values are:

- `non-interactive`
- `invisible`
- `managed`

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #2417

### CODE REVIEW

**Comment by LinusU** [comment]
@jacobbednarz could you add the `workflow/skip-changelog-entry` tag?

> #### Changes that should _not_ have a CHANGELOG entry
> 
> - Resource and provider documentation updates

**Comment by LinusU** [comment]
Hmm, seems like the best thing would be if the documentation generator could look at the `stringvalidator.OneOf` validator and do this automatically? 🤔 

I've added the text to `MarkdownDescription` now 🚀

**Comment by jacobbednarz** [comment]
> Hmm, seems like the best thing would be if the documentation generator could look at the `stringvalidator.OneOf` validator and do this automatically? 🤔

this is a known restriction of the plugin framework. it is already tracked upstream via https://github.com/hashicorp/terraform-plugin-framework/issues/625

**Comment by jacobbednarz** [comment]
thanks for this one @LinusU 🏆

**Comment by LinusU** [comment]
Thanks for the quick pull!

btw. do you know approximately when #2413 will be released? I ran into basically all issues covered by that one and had to `terraform state rm` to recover, and I would imagine that anyone else trying to use Turnstile via Terraform would have the same problems...

**Comment by jacobbednarz** [comment]
the release process (including how to calculate the next one) is documented at https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/release-process.md.

if you need to use an unreleased version of the provider, there is also some steps you can use from https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/using-non-released-versions.md to run whatever version you're after.

**Pull request merged**
