### PR TITLE
resource/cloudflare_waiting_room: Add cookie_suffix & additional_routes to the WR resource

### PR DESCRIPTION
**Pull request by yj7o5**
Add new fields `additional_routes` and `cookie_suffix` to the Waiting Room resource.

### CODE REVIEW

**Comment by yj7o5** [comment]
Waiting on this https://github.com/cloudflare/cloudflare-go/pull/1311 to get the WR schema definition to get updated to get the tests passing.

**Comment by jacobbednarz** [comment]
please remove the version bump from this PR; we have automation that handles that and avoids per branch conflicts.

**Comment by jacobbednarz** [comment]
acceptance tests all passing

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareWaitingRoom_" -count 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareWaitingRoom_Create
=== PAUSE TestAccCloudflareWaitingRoom_Create
=== CONT  TestAccCloudflareWaitingRoom_Create
--- PASS: TestAccCloudflareWaitingRoom_Create (6.43s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	7.333s
```

**Comment by jacobbednarz** [comment]
thanks for the PR @yj7o5 🤘 you rock.

**Pull request merged**
