### PR TITLE
resource/healthcheck: Retry hostname resolution errors

### LINKED ISSUE #786: Health checks are not able to see newly created DNS resources
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12.28

### Affected Resource(s)
Please list the resources as a list, for example:
cloudflare_record
cloudflare_healthcheck

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
If I create a DNS record, and then want to create a health check for that site, it should create fine

### Actual Behavior
module.www-dns.cloudflare_record.record: Creating...
module.www-dns.cloudflare_record.record: Creation complete after 1s [id=056f8d5ef3f06a9a2ce4c0ed1299f15f]
module.www-dns.cloudflare_healthcheck.health_check: Creating...

Error: error creating standalone healthcheck: error from makeRequest: HTTP status 400: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 1002,\n      \"message\": \"lookup www.mysite.com on 10.32.0.10:53: no such host\"\n    }\n  ],\n  \"messages\": []\n}\n"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

resource "cloudflare_record" "record" {
  zone_id = lookup(data.cloudflare_zones.zone.zones[0], "id")
  name    = var.name
  value   = var.value
  type    = var.type
  proxied = var.proxy_enabled
}

resource "cloudflare_healthcheck" "health_check" {
  zone_id                      = lookup(data.cloudflare_zones.zone.zones[0], "id")
  name                         = "${var.env}-${var.name}"
  description                  = var.description
  address                      = cloudflare_record.record.hostname
  suspended                    = false
  check_regions                = ["WNAM","ENAM"]
  notification_suspended       = false
  notification_email_addresses = ["ibinder@binderworld.com"]
  type                         = "HTTPS"
  port                         = "443"
  method                       = "GET"
  path                         = "/"
  expected_codes               = ["2xx"]
  follow_redirects             = true
  allow_insecure               = false
  timeout                      = 10
  retries                      = 2
  interval                     = 60
  consecutive_fails            = 3
  consecutive_successes        = 2
}

### PR DESCRIPTION
**Pull request by jacobbednarz**
This implements the retry logic which will allow leeway when a
Cloudflare DNS record is created at the same time as the healthcheck and
the former hasn't yet propogated to other systems.

By implementing this, we do create a much longer feedback loop to the
user when the record in use is indeed broken. It will go from ~ 1s to a
maximum of 30s. Should someone be debugging this scenario, they will
still receive the error in the Terraform logs but it will make
discoverying the underlying cause harder.

Fixes #786

### CODE REVIEW

**Comment by jacobbednarz** [comment]
@patryk thoughts as a maintainer? @cehrig as the original implementor (and assuming you're using it a bit), do you have any thoughts? This is a pretty significant slowdown if you do hit this scenario due to a broken hostname being added in.

**Comment by cehrig** [comment]
Interesting, I did not come across this issue yet. It pretty much leaves us to retrying since the API is missing a bypass of the hostname check. :+1:  for the implementation and TIL that there's a timeout capability.

**Comment by jacobbednarz** [comment]
Had an out of band conversation with @patryk on this one and we're willing to give it a go despite the potential drawback of sitting there for 30s if you input the hostname incorrectly.

**Comment by patryk** [comment]
Sorry for not responding here. I think the delay that happens most often should be limited to single seconds, mainly related to underlying replication lag in the storage layer. We could tune it later if needed.

**Pull request merged**
