### PR TITLE
Update go.mod

### PR DESCRIPTION
**Pull request by y0k41sec**
correcting the repo

### CODE REVIEW

**Review by ganzcf — APPROVED** [review]
github user denis-tingajkin has renamed their account to denis-tingaikin

**Comment by jacobbednarz** [comment]
going to hold on this for a week or so to confirm validity of the change.

**Comment by patryk** [comment]
Looks to be valid, GitHub redirects:
```
$ curl https://github.com/denis-tingajkin/go-header -v 2>&1 | grep -i location:
< location: https://github.com/denis-tingaikin/go-header
```

**Comment by jacobbednarz** [comment]
@y0k41sec this is missing the changes to the `go.sum` file. you'll need to add it for us to merge this PR.

**Comment by y0k41sec** [comment]
Hi, it looks like this is an indirect dependency which implies that you are not using this dependency within the project, but there is some module that imports them. I find that go.sum creates a hash, so this is not a vulnerability, there is no risk of downloading a malicious dependency in this case. I'll close this pull request, thanks everyone for taking a look.

**Pull request closed without merging**
