### PR TITLE
WIP Support for Cloudflare Queue Consumers as a resource

### PR DESCRIPTION
**Pull request by OilyLime**
Parking this here for now, but will be returned to and somewhat overhauled following some forthcoming API changes.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
closing this out for now since it hasn't progressed and for new resources, we should be targetting the `terraform-plugin-framework` and avoid a bunch of zero/nil issues within Terraform. do drop me a message if you plan to reopen this one and we can walk through it.

**Comment by vpctorr** [comment]
Hey there! I was wondering if we could expect to see queue consumer anytime soon?

**Comment by SteffTek** [comment]
**BUMP** Because I really need this for my next project. I'll need to create a bunch of queues for each customer and don't have the patience to click though the UI every time (╯°□°)╯︵ ┻━┻

**Comment by wsierakowski** [comment]
We are also adopting queues in our TF-provisioned project and have just encountered the same obstacle. It would be incredibly useful to be able to consistently manage everything from the single Terraform script if the support for a queue consumer was added to the provider.

**Comment by SteffTek** [comment]
@wsierakowski we "fixed" this problem by having a wrangler cli command after terraform, it's not pretty, and we need to delete the queue consumer and reapply it because otherwise it'll crash, but it works... Sadly

**Comment by wsierakowski** [comment]
> @wsierakowski we "fixed" this problem by having a wrangler cli command after terraform, it's not pretty, and we need to delete the queue consumer and reapply it because otherwise it'll crash, but it works... Sadly

We temporarily implemented a script that imperatively provisions the queue using the API https://developers.cloudflare.com/api/operations/queue-v2-create-queue. Hopefully it won't take long to have the ability to manage the entire project's infra with TF!

**Pull request closed without merging**
