### PR TITLE
enhancement: Add support for resolver policies

### PR DESCRIPTION
**Pull request by joebb97**

### CODE REVIEW

**Comment by joebb97** [comment]
I couldn't get `TestProvider` to pass, it says

```

**Comment by joebb97** [comment]
think i found a bug
`panic: interface conversion: interface {} is bool, not *bool`

**Comment by joebb97** [comment]
This PR is dependent upon a change to cloudflare-go. That PR is here https://github.com/cloudflare/cloudflare-go/pull/1615

**Comment by jacobbednarz** [comment]
acceptance tests all passing

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareTeamsRule_" -count 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareTeamsRule_Basic
--- PASS: TestAccCloudflareTeamsRule_Basic (7.50s)
=== RUN   TestAccCloudflareTeamsRule_NoSettings
--- PASS: TestAccCloudflareTeamsRule_NoSettings (10.30s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	18.921s
```

**Pull request merged**
