### PR TITLE
FLPROD-796: Register snippet and snippet_rules resources

### PR DESCRIPTION
**Pull request by WowVeryLogin**
Depends on cloudflare/cloudflare-go#3596 and https://github.com/cloudflare/cloudflare-go/pull/3669

### CODE REVIEW

**Comment by jacobbednarz** [comment]
`cloudflare_snippet` looks fine

```
TF_ACC=1 go test ./internal/framework/service/snippets/ -run "^TestAcc" -count 1 -v
=== RUN   TestAccCloudflareSnippet
=== PAUSE TestAccCloudflareSnippet
=== CONT  TestAccCloudflareSnippet
--- PASS: TestAccCloudflareSnippet (5.15s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/snippets	6.389s
```

however, `cloudflare_snippet_rules` is having issues with the decoding of the json

```
=== RUN   TestAccCloudflareSnippetRules
=== PAUSE TestAccCloudflareSnippetRules
=== CONT  TestAccCloudflareSnippetRules
    resource_test.go:55: Step 1/2 error: Error running apply: exit status 1
        
        Error: failed to create snippet rules
        
          with cloudflare_snippet_rules.qciadqjjip,
          on terraform_plugin_test.tf line 12, in resource "cloudflare_snippet_rules" "qciadqjjip":
          12:   resource "cloudflare_snippet_rules" "qciadqjjip" {
        
        can not decode parameters json
--- FAIL: TestAccCloudflareSnippetRules (0.90s)
FAIL
FAIL	github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/snippet_rules	2.144s
FAIL
```

**Comment by WowVeryLogin** [comment]
Yeah, it's the answer from snippets-api service. Should be fixed with: https://github.com/cloudflare/cloudflare-go/pull/3669

**Comment by jacobbednarz** [comment]
ah, so there is another dependent PR. sorry, missed that.

**Comment by travisby** [comment]
Now that https://github.com/cloudflare/cloudflare-go/pull/3669 is merged, can we roll this out? :D

**Comment by jacobbednarz** [comment]
acceptance tests all passing here

```
=== RUN   TestAccCloudflareSnippetRules
=== PAUSE TestAccCloudflareSnippetRules
=== CONT  TestAccCloudflareSnippetRules
--- PASS: TestAccCloudflareSnippetRules (14.26s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/snippet_rules	15.629s
```

**Pull request merged**
