### PR TITLE
Add support logpush filters

### LINKED ISSUE #1632: cloudflare_logpush_job - Support filter
### Current Terraform and Cloudflare provider version

Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.14.0
+ provider registry.terraform.io/hashicorp/aws v4.14.0

### Description

The objective is to support filter on logpush job.
Check https://developers.cloudflare.com/logs/reference/logpush-api-configuration/filters/

### Use cases

Allow to create logpush job with filter like for example, only export requests with request host equals to "www.example.com" or "example.com".

### Potential Terraform configuration

```hcl
resource "cloudflare_logpush_job" "this" {
  zone_id = cloudflare_zone.this.id

  name    = "my-test-job"
  enabled = true

  destination_conf    = "s3://cloudflare-logpush-test/{DATE}?region=us-east-1&sse=AES256"
  ownership_challenge = data.aws_s3_object.this.body

  dataset         = "http_requests"
  logpull_options = "fields=ClientIP,ClientRequestHost,ClientRequestMethod,ClientRequestPath,ClientRequestProtocol,ClientRequestReferer,ClientRequestScheme,ClientRequestURI,ClientRequestUserAgent,EdgeEndTimestamp,EdgeResponseBytes,EdgeResponseStatus&timestamps=rfc3339"

  filter = jsonencode({
    where = {
        key = "ClientRequestHost"
        operator = "in"
        value = [
          "example.com",
          "www.example.com"
        ]
      }
  })
}
```

### References

_No response_

### PR DESCRIPTION
**Pull request by yknx4**
closes #1632

Hello ~
Our team at Shopify worked on added support for LogpushJob filter in https://github.com/cloudflare/cloudflare-go/pull/915 and now we are looking to updating the terraform-provider

Right now this depends on the master build of `cloudflare-go` so it probably requires a release on your side. But it would help to have some eyes on it. 

```release-note:enhancement
schema/logpush_job: Add `filter` attribute
resource/logpush_job: Add `filter` field support
```

## Pending

- [x] Use next release of `cloudflare-go` instead of master branch

## Examples
_This has some redacted fields_
### Config
```tf
resource "cloudflare_logpush_job" "lowvolume" {
  name                = "${local.domain}-HTTP-lowvolume-request-logs"
  zone_id             = cloudflare_zone.zone.id
  destination_conf    = "gs://${local.log_bucket}/cloudflare/http/${local.domain}/{DATE}"
  ownership_challenge = local.cloudflare_logpush_ownership_challenge_response
  dataset             = "http_requests"
  logpull_options     = "timestamps=unixnano&....."
  filter = jsonencode({
    "where" : {
      "and" : [
        {
          "key" : "ClientRequestHost",
          "operator" : "in",
          "value" : [
            "foo.mydomain2.com",
            "cdn.myapp.com",
            "cdn.mydomain2.net",
            "bar.mydomain2.com",
            "myapp-assets.mydomain2.com",
            "myapp-assets.mydomain2.net"
          ]
        },
        {
          "key" : "ClientRequestPath",
          "operator" : "!startsWith",
          "value" : "/asset/"
        },
        {
          "key" : "ClientRequestPath",
          "operator" : "!startsWith",
          "value" : "/admin/"
        }
    ] }
  })

  enabled = true
}
```

### Output
```
Terraform will perform the following actions:

  # cloudflare_logpush_job.highvolume will be updated in-place
  ~ resource "cloudflare_logpush_job" "highvolume" {
      ~ enabled             = true -> false
        id                  = "77975"
        name                = "apps.myapp.com-HTTP-highvolume-request-logs"
        # (7 unchanged attributes hidden)
    }

  # cloudflare_logpush_job.lowvolume will be updated in-place
  ~ resource "cloudflare_logpush_job" "lowvolume" {
      ~ enabled             = true -> false
      ~ filter              = jsonencode(
          ~ {
              ~ where = {
                  ~ and = [
                        {
                            key      = "ClientRequestHost"
                            operator = "in"
                            value    = [
                                "foo.mydomain2.com",
                                "cdn.myapp.com",
                                "cdn.mydomain2.net",
                                "bar.mydomain2.com",
                                "myapp-assets.mydomain2.com",
                                "myapp-assets.mydomain2.net",
                            ]
                        },
                      ~ {
                          - and      = [
                              - {
                                  - key      = "ClientRequestPath"
                                  - operator = "!startsWith"
                                  - value    = "/assets/"
                                },
                              - {
                                  - key      = "ClientRequestPath"
                                  - operator = "!startsWith"
                                  - value    = "/admin/"
                                },
                            ] -> null
                          + key      = "ClientRequestPath"
                          + operator = "!startsWith"
                          + value    = "/assets/"
                        },
                      + {
                          + key      = "ClientRequestPath"
                          + operator = "!startsWith"
                          + value    = "/admin/"
                        },
                    ]
                }
            }
        )
        id                  = "99999"
        name                = "apps.myapp.com-HTTP-lowvolume-request-logs"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_logpush_job.highvolume: Modifying... [id=77975]
cloudflare_logpush_job.lowvolume: Modifying... [id=77979]
cloudflare_logpush_job.lowvolume: Modifications complete after 2s [id=77979]
cloudflare_logpush_job.highvolume: Modifications complete after 2s [id=77975]
```

### CODE REVIEW

**Review by jacobbednarz — COMMENTED** [review]
looking good! we'll need to:

- add the changelog entry 
- update the registry documentation (https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/website/docs/r/logpush_job.html.markdown)

once those are in, i'll run some acceptance tests and get this marked as ready for merge.

**Review by jacobbednarz — APPROVED** [review]
LGTM! just waiting on the next cloudflare-go release to land. locally this looks good.

**Comment by jacobbednarz** [comment]
i attempted to automatically update this branch for you now that cloudflare-go@v0.41.0 has landed but it looks to be blocked in your fork. feel free to bump it and we can kick off the acceptance test suite for you.

**Comment by yknx4** [comment]
@jacobbednarz ok. Thank you very much for your support

**Comment by jacobbednarz** [comment]
migrated to autogen docs in #1686

**Pull request merged**
